{{- if .Values.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
data:
{{- range $config := .Values.config }}
  {{ $config.name }}: |
{{ $config.content | indent 4 -}}
{{- end -}}
{{- end -}}