{{- if and .Values.zwavejs.enabled (and .Values.zwavejs.persistence.enabled (not .Values.zwavejs.persistence.existingClaim)) (not .Values.zwavejs.persistence.hostPath) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "chart.fullname" . }}-zwavejs
  namespace: {{ .Release.Namespace }}
{{- with .Values.zwavejs.persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.zwavejs.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.zwavejs.persistence.size | quote }}
{{- if .Values.zwavejs.persistence.storageClass }}
{{- if (eq "-" .Values.zwavejs.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.zwavejs.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}