{{- if and .Values.zwavejs.enabled .Values.zwavejs.settings.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-zwave-settings
stringData:
  settings.json: |
    {
      "mqtt": {
        "name": "zwave-js-ui",
        "host": "localhost",
        "port": 1883,
        "qos": 1,
        "prefix": "zwave",
        "reconnectPeriod": 3000,
        "retain": true,
        "clean": true,
        "auth": false,
        "_ca": "",
        "ca": "",
        "_cert": "",
        "cert": "",
        "_key": "",
        "key": ""
      },
      "gateway": {
        "type": 0,
        "plugins": [],
        "authEnabled": false,
        "payloadType": 0,
        "nodeNames": true,
        "hassDiscovery": false,
        "discoveryPrefix": "homeassistant",
        "logEnabled": false,
        "logLevel": "debug",
        "logToFile": false,
        "values": [],
        "jobs": []
      },
      "zwave": {
        "port": "/dev/zwave",
        "allowBootloaderOnly": false,
        "commandsTimeout": 30,
        "logLevel": "debug",
        "logEnabled": true,
        "securityKeys": {},
        "deviceConfigPriorityDir": "/usr/src/app/store/config",
        "logToFile": true,
        "maxFiles": 7,
        "serverEnabled": false,
        "serverServiceDiscoveryDisabled": false,
        "enableSoftReset": true,
        "enableStatistics": false,
        "serverPort": 3000,
        "maxNodeEventsQueueSize": 100,
        "higherReportsTimeout": false,
        "disclaimerVersion": 1
      },
      "backup": {
        "storeBackup": false,
        "storeCron": "0 0 * * *",
        "storeKeep": 7,
        "nvmBackup": false,
        "nvmBackupOnEvent": false,
        "nvmCron": "0 0 * * *",
        "nvmKeep": 7
      }
    }
{{- end }}