{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zwave-js-ui.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: websocket
      port: 3000
      targetPort: websocket
  selector:
    name: zwave
{{- end }}
